version: '3.3'

services:
    nginx:
        container_name: milkstore_nginx
        image: nginx:1.21.6-alpine
        ports:
            - "80:80"
        volumes:
            - ./milk-app:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: always
        networks:
            - milkstore_network

    app:
        container_name: milkstore_app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - ./milk-app:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - milkstore_network

    database:
        container_name: milkstore_database
        image: library/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cdmllove
            MYSQL_USER: mark
            MYSQL_PASSWORD: cdmllove
            MYSQL_DATABASE: milkstore
        volumes:
            - milk_store_data:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - milkstore_network

    phpmyadmin:
        container_name: milkstore_phpmyadmin
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - '1234:80'
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: cdmllove
        networks:
            - milkstore_network

volumes:
    milk_store_data:
        driver: local

networks:
    milkstore_network:
        driver: bridge
